name: Deploy to InfinityFree

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpupload.net  # Hostname FTP d'InfinityFree
          username: si0_37858005  # Remplacez par votre nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }}  # Ajoutez votre mot de passe FTP comme secret
          local-dir: ./  # Répertoire à uploader
          server-dir: /htdocs/  # Répertoire cible sur InfinityFree
